---
- name: Download nginx source
  get_url:
    url: https://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
    dest: /tmp/nginx-{{ nginx_version }}.tar.gz

- name: Unarchive nginx
  unarchive:
    src: /tmp/nginx-{{ nginx_version }}.tar.gz
    dest: /tmp/
    remote_src: true
    mode: "0755"

- name: Configure  # noqa 301
  command: ./configure
  args:
    chdir: /tmp/nginx-{{ nginx_version }}

- name: Make
  make:
    chdir: /tmp/nginx-{{ nginx_version }}

- name: Make install
  become: true
  make:
    chdir: /tmp/nginx-{{ nginx_version }}
    target: install
